export const institutionData = {
  "chs": {
    id: "college",
    name: "Sunrise College for Higher Studies",
    shortName: "College for Higher Studies",
    code: "CHS",
    type: "College",
    affiliation: "University Affiliated",
    classes: "BA/B.Sc Programs",
    icon: "graduation-cap",
    color: "blue",
    description:
      "Comprehensive undergraduate education in Arts and Science streams with industry exposure, research opportunities, and career-oriented skill development.",
    established: "2012",
    students: "1500+",
    successRate: "95% Pass Rate",
    features: [
      "Industry internships and placement support",
      "Research projects and academic excellence programs",
      "Modern laboratories and equipment",
      "Experienced faculty with PhD qualifications",
      "Career counseling and guidance",
      "Digital library access",
    ],
    programs: [
      { name: "Bachelor of Arts", classes: "3 Years", description: "Multiple specializations available" },
      { name: "Bachelor of Science", classes: "3 Years", description: "PCM, PCB, Computer Science streams" },
      { name: "Commerce Stream", classes: "3 Years", description: "Accounting, Economics, Business Studies" },
    ],
    facilities: [
      "Modern Classrooms",
      "Research Labs",
      "Digital Library",
      "Computer Center",
      "Seminar Halls",
      "Student Common Room",
      "Placement Cell",
      "Hostel Facility",
    ],
    achievements: ["95% Placement Record", "University Rank Holders", "Research Publications", "Industry Partnerships"],
  },
  "ips": {
    id: "school",
    name: "Sunrise International Public School",
    shortName: "International Public School",
    code: "IPS",
    type: "School",
    affiliation: "CBSE Affiliated",
    classes: "Classes I-XII",
    icon: "book-open",
    color: "orange",
    description:
      "Our flagship institution providing world-class CBSE education with a focus on academic excellence, character building, and holistic development of students.",
    established: "2009",
    students: "2000+",
    successRate: "100% Board Results",
    features: [
      "Smart classrooms with digital learning tools",
      "Comprehensive sports and arts programs",
      "Experienced CBSE-trained faculty",
      "Regular parent-teacher interactions",
      "State-of-the-art laboratories",
      "Library with 10,000+ books",
    ],
    programs: [
      { name: "Primary Education", classes: "Classes I-V", description: "Foundation building with play-way method" },
      { name: "Middle School", classes: "Classes VI-VIII", description: "Conceptual learning with practical approach" },
      { name: "Secondary", classes: "Classes IX-X", description: "Board preparation with career guidance" },
      {
        name: "Senior Secondary",
        classes: "Classes XI-XII",
        description: "Stream specialization (Science/Commerce/Arts)",
      },
    ],
    facilities: [
      "Smart Classrooms",
      "Science Laboratories",
      "Computer Lab",
      "Library",
      "Sports Complex",
      "Art & Music Room",
      "Cafeteria",
      "Medical Room",
    ],
    achievements: [
      "100% Pass Rate in CBSE Boards",
      "State Topper in Mathematics",
      "Best School Award 2023",
      "Excellence in Sports",
    ],
  },
  "pc": {
    id: "pharmacy",
    name: "Sunrise Pharmacy College",
    shortName: "Pharmacy College",
    code: "PC",
    type: "Professional College",
    affiliation: "PCI Approved",
    classes: "D.Pharma/B.Pharma",
    icon: "stethoscope",
    color: "green",
    description:
      "Professional pharmacy education with state-of-the-art laboratories, clinical training, and industry partnerships to prepare competent healthcare professionals.",
    established: "2018",
    students: "800+",
    successRate: "90% Placement",
    features: [
      "Modern pharmaceutical laboratories and equipment",
      "Clinical training in partner hospitals",
      "Industry internships with leading pharma companies",
      "Research opportunities in drug development",
      "PCI approved curriculum",
      "Experienced faculty from industry",
    ],
    programs: [
      { name: "Diploma in Pharmacy", classes: "2 Years", description: "D.Pharma with practical training" },
      { name: "Bachelor of Pharmacy", classes: "4 Years", description: "B.Pharma with research opportunities" },
      { name: "Industrial Training", classes: "6 Months", description: "Hands-on industry experience" },
    ],
    facilities: [
      "Pharmaceutical Labs",
      "Research Center",
      "Drug Testing Lab",
      "Clinical Training",
      "Industry Partnerships",
      "Modern Equipment",
      "Placement Cell",
      "Hospital Tie-ups",
    ],
    achievements: ["90% Placement Rate", "Industry Partnerships", "Research Publications", "PCI Recognition"],
  },
  "fa": {
    id: "foundation",
    name: "Sunrise Foundation Academy",
    shortName: "Foundation Academy",
    code: "FA",
    type: "Coaching Institute",
    affiliation: "Expert Coaching",
    classes: "IIT-JEE/NEET",
    icon: "calculator",
    color: "purple",
    description:
      "Specialized coaching institute for IIT-JEE, NEET, and other competitive examinations with expert faculty, proven methodologies, and outstanding results.",
    established: "2015",
    students: "700+",
    successRate: "150+ Selections",
    features: [
      "IIT-JEE Main & Advanced preparation",
      "NEET (Medical entrance) coaching",
      "Foundation courses for Classes 8-10",
      "Regular mock tests and performance analysis",
      "Expert faculty from IITs/NITs",
      "Small batch sizes for personal attention",
    ],
    programs: [
      { name: "IIT-JEE Preparation", classes: "2 Years", description: "Main & Advanced coaching" },
      { name: "NEET Coaching", classes: "2 Years", description: "Medical entrance preparation" },
      { name: "Foundation Course", classes: "Classes 8-10", description: "Early preparation program" },
      { name: "Crash Course", classes: "6 Months", description: "Intensive revision program" },
    ],
    facilities: [
      "AC Classrooms",
      "Digital Teaching",
      "Test Series",
      "Study Material",
      "Doubt Clearing",
      "Performance Analysis",
      "Parent Meetings",
      "Online Portal",
    ],
    achievements: [
      "150+ IIT/NIT Selections",
      "200+ Medical Selections",
      "Top Rankers Every Year",
      "Expert Faculty Team",
    ],
  },
}
